#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const archiver = require('archiver');

// Create a zip archive of the project
function createProjectArchive() {
  const output = fs.createWriteStream('go-ahead-security-project.zip');
  const archive = archiver('zip', {
    zlib: { level: 9 } // Maximum compression
  });

  output.on('close', function() {
    console.log('✅ Project archived successfully!');
    console.log(`📦 Archive size: ${archive.pointer()} bytes`);
    console.log('📁 File: go-ahead-security-project.zip');
  });

  archive.on('error', function(err) {
    console.error('❌ Error creating archive:', err);
    throw err;
  });

  archive.pipe(output);

  // Add all project files except node_modules and other unnecessary files
  const filesToExclude = [
    'node_modules/**',
    '.git/**',
    '*.log',
    '.DS_Store',
    'Thumbs.db',
    'go-ahead-security-project.zip',
    'download-project.js'
  ];

  archive.glob('**/*', {
    ignore: filesToExclude,
    dot: true
  });

  archive.finalize();
}

// Create project info file
function createProjectInfo() {
  const projectInfo = {
    name: "Go Ahead Security - Management System",
    description: "A comprehensive security company management system built with React, TypeScript, and Tailwind CSS",
    version: "1.0.0",
    author: "Generated by Bolt",
    technologies: [
      "React 18",
      "TypeScript",
      "Tailwind CSS",
      "Vite",
      "Lucide React Icons"
    ],
    features: [
      "Employee Management",
      "Client Management", 
      "Site Management",
      "Dashboard Analytics",
      "Responsive Design",
      "French Localization"
    ],
    setup: {
      "1": "Extract the project files",
      "2": "Run 'npm install' to install dependencies",
      "3": "Run 'npm run dev' to start the development server",
      "4": "Open http://localhost:5173 in your browser"
    },
    structure: {
      "src/": "Source code directory",
      "src/components/": "React components organized by feature",
      "src/contexts/": "React context providers for state management",
      "src/types/": "TypeScript type definitions",
      "src/utils/": "Utility functions and sample data",
      "public/": "Static assets",
      "package.json": "Project dependencies and scripts"
    }
  };

  fs.writeFileSync('PROJECT_INFO.json', JSON.stringify(projectInfo, null, 2));
  console.log('📋 Created PROJECT_INFO.json with setup instructions');
}

// Create README file
function createReadme() {
  const readme = `# Go Ahead Security - Management System

A comprehensive security company management system built with modern web technologies.

## 🚀 Features

- **Employee Management**: Complete HR system with certifications tracking
- **Client Management**: Client contracts and relationship management  
- **Site Management**: Security site locations and patrol routes
- **Dashboard Analytics**: Real-time business metrics and insights
- **Responsive Design**: Works perfectly on desktop, tablet, and mobile
- **French Localization**: Fully localized interface in French

## 🛠️ Technologies

- **React 18** - Modern UI library
- **TypeScript** - Type-safe development
- **Tailwind CSS** - Utility-first CSS framework
- **Vite** - Fast build tool and dev server
- **Lucide React** - Beautiful icon library

## 📦 Installation

1. Extract the project files to your desired location
2. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

3. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

4. Open your browser and navigate to \`http://localhost:5173\`

## 🏗️ Project Structure

\`\`\`
src/
├── components/          # React components
│   ├── Dashboard/       # Dashboard components
│   ├── HR/             # Human Resources components
│   ├── Layout/         # Layout components (Header, Sidebar)
│   └── Operations/     # Operations components (Clients, Sites)
├── contexts/           # React context providers
├── types/              # TypeScript type definitions
├── utils/              # Utility functions and sample data
└── main.tsx           # Application entry point
\`\`\`

## 🎯 Usage

The system includes sample data to demonstrate all features:

- **Dashboard**: Overview of company metrics and recent activities
- **HR Module**: Manage employees, certifications, and performance
- **Operations**: Handle clients and their service contracts
- **Sites**: Manage security locations and patrol routes

## 🔧 Development

- \`npm run dev\` - Start development server
- \`npm run build\` - Build for production
- \`npm run preview\` - Preview production build
- \`npm run lint\` - Run ESLint

## 📝 License

This project was generated using Bolt and is available for educational and commercial use.

## 🤝 Contributing

Feel free to fork this project and submit pull requests for any improvements.
`;

  fs.writeFileSync('README.md', readme);
  console.log('📖 Created README.md with project documentation');
}

// Main execution
console.log('🚀 Preparing Go Ahead Security project for download...\n');

createProjectInfo();
createReadme();

// Check if archiver is available, if not provide manual instructions
try {
  require.resolve('archiver');
  createProjectArchive();
} catch (e) {
  console.log('📦 To create a zip archive, install archiver and run this script:');
  console.log('   npm install archiver');
  console.log('   node download-project.js');
  console.log('\n📁 Alternatively, you can manually copy all project files.');
}

console.log('\n✨ Project is ready for download!');